import { useRef, useState } from "react";
import type { FormEvent } from "react";
import { Link, useLocation, useNavigate } from "react-router";
import { acquireTurnstileToken, api, ApiError, TurnstileClientError } from "../api";
import { Layout } from "../components/Layout";
import { ErrorSummary, StateNotice } from "../components/Status";

const message = (error: unknown) => error instanceof TurnstileClientError || error instanceof ApiError && error.code === "TURNSTILE_REJECTED" ? "The anti-abuse check did not complete. Check your connection and try again." : error instanceof ApiError && error.code === "EMAIL_NOT_VERIFIED" ? "Verify your email from the mailbox message before logging in." : "We could not complete that request. Check the entered details and try again.";
export const destination = (search: string) => {
  const value = new URLSearchParams(search).get("next");
  if (!value || !value.startsWith("/") || value.startsWith("//")) return "/";
  try {
    // Reject slash-normalization tricks before Router gets an opportunity to navigate.
    if (value.includes("\\") || decodeURIComponent(value).includes("\\")) return "/";
    const parsed = new URL(value, location.origin);
    return parsed.origin === location.origin && parsed.pathname.startsWith("/") && !parsed.pathname.startsWith("//") ? `${parsed.pathname}${parsed.search}${parsed.hash}` : "/";
  } catch { return "/"; }
};
const withNext = (path: string, next: string) => `${path}?next=${encodeURIComponent(next)}`;

export function SignUpPage() {
  const location = useLocation(); const turnstileTarget = useRef<HTMLDivElement>(null); const [error, setError] = useState(""); const [sent, setSent] = useState(false); const [pending, setPending] = useState(false); const next = destination(location.search);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); try { await api.signUp(String(form.get("name")), String(form.get("email")), String(form.get("password")), { turnstileToken: await acquireTurnstileToken(turnstileTarget.current) }); setSent(true); } catch (e) { setError(message(e)); } finally { setPending(false); } };
  return <Layout><h1 data-testid="current-sign-up-spa">Create account</h1><ErrorSummary message={error}/>{sent ? <StateNotice title="Check your mailbox"><p>We sent a verification link. Verify your address, then <Link to={withNext("/login", next)}>log in</Link>.</p></StateNotice> : <form onSubmit={submit} aria-busy={pending}><p><label>Name<br/><input name="name" required autoComplete="name" disabled={pending}/></label></p><p><label>Email address<br/><input name="email" type="email" required autoComplete="email" disabled={pending}/></label></p><p><label>Password<br/><input name="password" type="password" minLength={8} required autoComplete="new-password" disabled={pending}/></label></p><div ref={turnstileTarget}/><button className="primary-action" type="submit" disabled={pending}>{pending ? "Creating account…" : "Create account"}</button></form>}<p><Link to={withNext("/login", next)}>Already have an account? Log in</Link></p></Layout>;
}
export function LoginPage() {
  const nav = useNavigate(); const location = useLocation(); const turnstileTarget = useRef<HTMLDivElement>(null); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const next = destination(location.search);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); try { await api.signIn(String(form.get("email")), String(form.get("password")), { turnstileToken: await acquireTurnstileToken(turnstileTarget.current) }); nav(next); } catch (e) { setError(message(e)); } finally { setPending(false); } };
  return <Layout><h1>Log in</h1><ErrorSummary message={error}/><form onSubmit={submit} aria-busy={pending}><p><label>Email address<br/><input name="email" type="email" required autoComplete="email" disabled={pending}/></label></p><p><label>Password<br/><input name="password" type="password" required autoComplete="current-password" disabled={pending}/></label></p><div ref={turnstileTarget}/><button className="primary-action" type="submit" disabled={pending}>{pending ? "Logging in…" : "Log in"}</button></form><p><Link to={withNext("/forgot-password", next)}>Forgot password?</Link> · <Link to={withNext("/sign-up", next)}>Create account</Link></p></Layout>;
}
export function ForgotPasswordPage() { const location = useLocation(); const next = destination(location.search); const [done, setDone] = useState(false); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setPending(true); setError(""); try { await api.forgotPassword(String(new FormData(e.currentTarget).get("email")), next); setDone(true); } catch (error) { setError(message(error)); } finally { setPending(false); } }; return <Layout><h1>Reset password</h1><ErrorSummary message={error}/>{done ? <StateNotice title="Check your mailbox"><p>If that address has an account, it has reset instructions.</p></StateNotice> : <form onSubmit={submit} aria-busy={pending}><label>Email address<br/><input name="email" type="email" required autoComplete="email" disabled={pending}/></label><p><button className="primary-action" disabled={pending}>{pending ? "Sending instructions…" : "Send reset instructions"}</button></p></form>}</Layout>; }
export function ResetPasswordPage() { const nav = useNavigate(); const location = useLocation(); const token = new URLSearchParams(location.search).get("token") ?? ""; const next = destination(location.search); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setPending(true); setError(""); try { await api.resetPassword(token, String(new FormData(e.currentTarget).get("password"))); nav(withNext("/login", next)); } catch (error) { setError(message(error)); } finally { setPending(false); } }; return <Layout><h1>Choose a new password</h1><ErrorSummary message={error}/><form onSubmit={submit} aria-busy={pending}><label>New password<br/><input name="password" type="password" minLength={8} required autoComplete="new-password" disabled={pending}/></label><p><button className="primary-action" disabled={pending}>{pending ? "Resetting password…" : "Reset password"}</button></p></form></Layout>; }
